apiVersion: v1
kind: Namespace
metadata:
  name: security-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  namespace: security-playground
  labels:
    app.kubernetes.io/name: security-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-playground
    spec:
      containers:
        - name: security-playground
          image: jasonumiker/security-playground:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: security-playground
  namespace: security-playground
  labels:
    app.kubernetes.io/name: security-playground
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30284
  selector:
    app.kubernetes.io/name: security-playground